# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Setting Up SSH Key
      run: | 
        mkdir ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/private
        sudo chmod 600 ~/.ssh/private
        eval $(ssh-agent)
        ssh-add ~/.ssh/private
        ssh pjp@patjpaj.me
      env:
        SSH_PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
      

    - name: Setting up remote and Pushing to Remote Server
      run: |
        git remote add live ssh://pjp@patjpaj.me/../var/repo/patjpaj.me.git
        git push live master

